export const GET_MOVIES_PENDING = "GET_MOVIES_PENDING";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAILED = "GET_MOVIES_FAILED";

export const SET_PAGE_NUBMER = "SET_PAGE_NUMBER";

export const GET_MOVIE_PENDING = "GET_MOVIE_PENDING";
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";
export const GET_MOVIE_FAILED = "GET_MOVIE_FAILED";
